server:
  port: 8080

spring:
  application:
    name: eureka-zuul

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka

zuul:
  ignored-services: '*'   #关闭默认路由配置规则
  routes:
    rout1:
      serviceId: eureka-provider-gatery
      path: /provider/**
#    eureka-customer:
#      path: /ec/**

    eureka-customer: /customer/**

